In [1]:
import numpy as np
arr = np.linspace(1,10,8)
print(arr)

[ 1.          2.28571429  3.57142857  4.85714286  6.14285714  7.42857143
  8.71428571 10.        ]


In [9]:
import numpy as np
arr = np.arange(10,20,3)
print(arr)
print(arr.shape)


[10 13 16 19]
(4,)


In [12]:
import numpy as np
arr = np.zeros((2,3),dtype=int)
print(arr)

[[0 0 0]
 [0 0 0]]
