Prints the array.
Prints its type.

In [ ]:
import numpy as np
arr =np.array([5, 15, 25, 35, 45])
print(arr)
print(type(arr))

Write a program that:

Import NumPy as np.
Create a NumPy array:
[12, 24, 36, 48, 60]
Print:
The array
Its type
Its number of dimensions (ndim)
Its shape (shape)

In [ ]:
import numpy as np
arr = np.array([[12, 24, 36, 48, 60],
                [30, 40, 50, 60, 70],
                [30, 40, 50, 60, 70],
                [30, 40, 50, 60, 70]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)

Import NumPy as np.
Create the following 3D array:
Import NumPy as np.
Create the following 3D array:

In [ ]:
import numpy as np
arr = [[1,2],[3,4]],[[5,6],[7,8]]
nparr = np.array(arr)
print(nparr,"\n",nparr.ndim,"\n",nparr.shape,"\n",nparr.size,"\n",nparr.dtype)

Create the following NumPy array:
[
    [[10, 20], [30, 40]],
    [[50, 60], [70, 80]],
    [[90, 100], [110, 120]]
]
Print:
The array
ndim
shape
size
dtype
Without running the program first, predict:
What will ndim be?
What will shape be?
What will size be?

In [ ]:
import numpy as np
arr = [[[10,20],[30,40]],[[50,60],[70,80]],[[90,100],[110,120]]]
np_arr = np.array(arr)
print(np_arr)
print(np_arr.ndim)
print(np_arr.shape)
print(np_arr.size)
print(np_arr.dtype)

In [ ]:
import numpy as np
arr = np.array([10, 20.5, 30, 40 ])
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)

Print the original array.
Print the original dtype.
Convert the array to int using astype().
Store it in a new variable named new_arr.
Print:
new_arr
new_arr.dtype
Finally, print the original array again.

In [ ]:
import numpy as np
arr = np.array([10.5, 20.7, 30.1, 40.9])
print("original array:- \n", arr)
print(arr.dtype)
new_int_arr= arr.astype(int)
print(new_int_arr,"\n",new_int_arr.dtype)
print(arr)

Your tasks:

Print the original array.
Print its dtype.
Convert it to boolean using astype(bool).
Store the result in bool_arr.
Print:
bool_arr
bool_arr.dtype

In [ ]:
import numpy as np

arr = np.array([1, 0, 5, 0, -2])
print("original array \n",arr)
print("datatypes:- \n",arr.dtype)
new_datatypes_array = arr.astype(bool)
print("it is new converted array from the existing array \n" 
,new_datatypes_array)
print("new array data types \n", new_datatypes_array.dtype)

Imports NumPy.
Creates a 2 × 5 array using np.zeros().
Prints:
the array
ndim
shape
size
dtype

⚠️ Don't use dtype=int yet. Let NumPy use its default data type.

In [ ]:
import numpy as np
arr = np.zeros((2,5))
print("zero array:- \n",arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

Write a program that:

Creates a 3 × 3 array using np.ones().
Prints:
the array
ndim
shape
size
dtype

In [19]:
import numpy as np
arr = np.ones((3,3))
print("array:- \n",arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

array:- 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
2
(3, 3)
9
float64


Write a program that:

Creates a 2 × 4 array using np.empty().
Prints:
the array
ndim
shape
size
dtype
Then replace every element with 7 using slicing.
Print the array again.

In [21]:
import numpy as np
arr = np.empty((2,4))
print("array:- \n",arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
arr[:]=7
print("new array:- \n",arr)

array:- 
 [[3.72117907e-315 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]]
2
(2, 4)
8
float64
new array:- 
 [[7. 7. 7. 7.]
 [7. 7. 7. 7.]]
