Prints the array.
Prints its type.

In [3]:
import numpy as np
arr =np.array([5, 15, 25, 35, 45])
print(arr)
print(type(arr))

[ 5 15 25 35 45]
<class 'numpy.ndarray'>


Write a program that:

Import NumPy as np.
Create a NumPy array:
[12, 24, 36, 48, 60]
Print:
The array
Its type
Its number of dimensions (ndim)
Its shape (shape)

In [2]:
import numpy as np
arr = np.array([[12, 24, 36, 48, 60],
                [30, 40, 50, 60, 70],
                [30, 40, 50, 60, 70],
                [30, 40, 50, 60, 70]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)

[[12 24 36 48 60]
 [30 40 50 60 70]
 [30 40 50 60 70]
 [30 40 50 60 70]]
<class 'numpy.ndarray'>
2
(4, 5)


Import NumPy as np.
Create the following 3D array:
Import NumPy as np.
Create the following 3D array:

In [13]:
import numpy as np
arr = [[1,2],[3,4]],[[5,6],[7,8]]
nparr = np.array(arr)
print(nparr,"\n",nparr.ndim,"\n",nparr.shape,"\n",nparr.size,"\n",nparr.dtype)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 
 3 
 (2, 2, 2) 
 8 
 int64


Create the following NumPy array:
[
    [[10, 20], [30, 40]],
    [[50, 60], [70, 80]],
    [[90, 100], [110, 120]]
]
Print:
The array
ndim
shape
size
dtype
Without running the program first, predict:
What will ndim be?
What will shape be?
What will size be?

In [18]:
import numpy as np
arr = [[[10,20],[30,40]],[[50,60],[70,80]],[[90,100],[110,120]]]
np_arr = np.array(arr)
print(np_arr)
print(np_arr.ndim)
print(np_arr.shape)
print(np_arr.size)
print(np_arr.dtype)

[[[ 10  20]
  [ 30  40]]

 [[ 50  60]
  [ 70  80]]

 [[ 90 100]
  [110 120]]]
3
(3, 2, 2)
12
int64


In [26]:
import numpy as np
arr = np.array([10, 20.5, 30, 40 ])
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)

[10.  20.5 30.  40. ]
1
(4,)
4


Print the original array.
Print the original dtype.
Convert the array to int using astype().
Store it in a new variable named new_arr.
Print:
new_arr
new_arr.dtype
Finally, print the original array again.

In [33]:
import numpy as np
arr = np.array([10.5, 20.7, 30.1, 40.9])
print("original array:- \n", arr)
print(arr.dtype)
new_int_arr= arr.astype(int)
print(new_int_arr,"\n",new_int_arr.dtype)
print(arr)



original array:- 
 [10.5 20.7 30.1 40.9]
float64
[10 20 30 40] 
 int64
[10.5 20.7 30.1 40.9]
