Prints the array.
Prints its type.

In [3]:
import numpy as np
arr =np.array([5, 15, 25, 35, 45])
print(arr)
print(type(arr))

[ 5 15 25 35 45]
<class 'numpy.ndarray'>


Write a program that:

Import NumPy as np.
Create a NumPy array:
[12, 24, 36, 48, 60]
Print:
The array
Its type
Its number of dimensions (ndim)
Its shape (shape)

In [2]:
import numpy as np
arr = np.array([[12, 24, 36, 48, 60],
                [30, 40, 50, 60, 70],
                [30, 40, 50, 60, 70],
                [30, 40, 50, 60, 70]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)

[[12 24 36 48 60]
 [30 40 50 60 70]
 [30 40 50 60 70]
 [30 40 50 60 70]]
<class 'numpy.ndarray'>
2
(4, 5)


Import NumPy as np.
Create the following 3D array:
Import NumPy as np.
Create the following 3D array:

In [13]:
import numpy as np
arr = [[1,2],[3,4]],[[5,6],[7,8]]
nparr = np.array(arr)
print(nparr,"\n",nparr.ndim,"\n",nparr.shape,"\n",nparr.size,"\n",nparr.dtype)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 
 3 
 (2, 2, 2) 
 8 
 int64
